// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TenderAnalytics.Infrastructure.Persistence;

#nullable disable

namespace TenderAnalytics.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714152316_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TenderAnalytics.Domain.Entities.Contract", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 2)
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("amount");

                    b.Property<string>("AwardId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("award_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Status")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TenderId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tender_id");

                    b.HasKey("Id");

                    b.HasIndex("AwardId")
                        .HasDatabaseName("ix_contracts_award_id");

                    b.HasIndex("TenderId")
                        .HasDatabaseName("ix_contracts_tender_id");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("TenderAnalytics.Domain.Entities.ContractSupplier", b =>
                {
                    b.Property<string>("ContractId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("contract_id");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_id");

                    b.HasKey("ContractId", "SupplierId");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_contract_suppliers_supplier_id");

                    b.ToTable("contract_suppliers", (string)null);
                });

            modelBuilder.Entity("TenderAnalytics.Domain.Entities.Supplier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Identifier")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("identifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("ux_suppliers_identifier")
                        .HasFilter("\"identifier\" IS NOT NULL");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("ix_suppliers_normalized_name");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("TenderAnalytics.Domain.Entities.Tender", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<string>("CpvCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("cpv_code");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<decimal>("ExpectedAmount")
                        .HasPrecision(19, 2)
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("expected_amount");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<string>("ProcuringEntityIdentifier")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("procuring_entity_identifier");

                    b.Property<string>("ProcuringEntityName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("procuring_entity_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ProcuringEntityIdentifier", "ProcuringEntityName")
                        .HasDatabaseName("ix_tenders_procuring_entity");

                    b.HasIndex("CpvCode", "Status", "DateCreated")
                        .HasDatabaseName("ix_tenders_cpv_status_date_created");

                    b.ToTable("tenders", (string)null);
                });

            modelBuilder.Entity("TenderAnalytics.Domain.Entities.Contract", b =>
                {
                    b.HasOne("TenderAnalytics.Domain.Entities.Tender", "Tender")
                        .WithMany("Contracts")
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("TenderAnalytics.Domain.Entities.ContractSupplier", b =>
                {
                    b.HasOne("TenderAnalytics.Domain.Entities.Contract", "Contract")
                        .WithMany("ContractSuppliers")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TenderAnalytics.Domain.Entities.Supplier", "Supplier")
                        .WithMany("ContractSuppliers")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TenderAnalytics.Domain.Entities.Contract", b =>
                {
                    b.Navigation("ContractSuppliers");
                });

            modelBuilder.Entity("TenderAnalytics.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("ContractSuppliers");
                });

            modelBuilder.Entity("TenderAnalytics.Domain.Entities.Tender", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
